PORT: 8080
WELCOME_MESSAGE: hi

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tracker_test
    #url: jdbc:mysql://localhost:3306/tracker_dev?user=tracker&useSSL=false&useTimezone=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: tracker
    password:
    # Keep the connection alive if idle for a long time (needed in production)
    #testWhileIdle:  true
    #validationQuery : SELECT 1

flyway:
  enabled: true

logging:
  level:
    org.flywaydb: DEBUG